# Generated by Django 4.2.16 on 2024-11-04 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='categroy',
            new_name='category',
        ),
    ]
